name: Garmentz
description: A new Flutter project.

# Dart and Flutter SDK constraints
environment:
  sdk: ">=3.5.3 <4.0.0"  # Dart SDK version
  flutter: ">=3.24.3 <4.0.0"  # Flutter SDK version

dependencies:
  flutter:
    sdk: flutter

  # Add the dependencies you need
  cupertino_icons: ^1.0.2  # For iOS styling
  provider: ^6.0.5         # State management solution
  http: ^0.13.6            # For HTTP requests to APIs
  image_picker: ^0.8.7     # For picking images from gallery or camera
  path_provider: ^2.0.11   # For file storage paths on the device
  shared_preferences: ^2.1.0  # For local storage of small data
  dio: ^5.0.5              # Alternative to the http package for network requests
  json_annotation: ^4.8.0  # For JSON parsing
  flutter_svg: ^1.1.6      # To handle SVG images
  cached_network_image: ^3.2.3 # For caching network images

  # Add more dependencies based on your project needs

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Dependency for code generation (optional, if using json_serializable, etc.)
  build_runner: ^2.3.3
  json_serializable: ^6.7.1  # For generating JSON serialization code

flutter:
  uses-material-design: true

  assets:
    - assets/images/  # Directory for image assets
    - assets/fonts/   # Directory for custom fonts (optional)

  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/Staatliches-Regular.ttf
          weight: 700
